name: Release
on:
    push:
        branches: [main]
        paths-ignore: ["**.md", ".gitignore", ".env.example"]
jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        if: "${{ contains(github.event.head_commit.message, 'chore: release') }}"
        env:
            BUILD_TODOIST_SECRETS: ${{ secrets.BUILD_TODOIST_SECRETS }}            
        steps:
            - uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Get version
              id: package-version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
            - name: Build
              run: bun run build
            - name: Calculate SHA
              id: shasum
              run: |
                echo "MAC_SHA=$(shasum -a 256 dist/boop-mac | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
            - name: Update Homebrew Formula
              run: |
                VERSION=${{ steps.package-version.outputs.VERSION }} \
                MAC_SHA=${{ steps.shasum.outputs.MAC_SHA }} \
                envsubst < homebrew/Formula/boop.rb > homebrew/Formula/boop.rb.tmp
                mv homebrew/Formula/boop.rb.tmp homebrew/Formula/boop.rb
            - name: Commit and Push Formula
              run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add homebrew/Formula/boop.rb
                git commit -m "chore: update homebrew formula for v${{ steps.package-version.outputs.VERSION }}"
                git push
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/boop-linux
                      dist/boop-windows
                      dist/boop-mac
                  tag_name: v${{ steps.package-version.outputs.VERSION }}
                  name: Release v${{ steps.package-version.outputs.VERSION }}
                  body: |
                      Automated release from commit: ${{ github.event.head_commit.message }}
                      
                      ## Installation
                      
                      ```bash
                      brew tap kshehadeh/boop
                      brew install boop
                      ```
